version: '3.8'

services:
  web:
    build: .
    container_name: snack_web
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - snack-net
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: snack_pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - snack-net

volumes:
  pgadmin_data:

networks:
  snack-net:
    driver: bridge
